//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emonti_Optometrist_Website
{

    public partial class BookAppointment
    {

        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.DropDownList ddlAppointmentType;

        protected global::System.Web.UI.WebControls.DropDownList ddlOptometrist;

        protected global::System.Web.UI.HtmlControls.HtmlInputText inputDate;

        protected global::System.Web.UI.HtmlControls.HtmlSelect ddlTimeSlot;

        protected global::System.Web.UI.WebControls.HiddenField hfCustomerName;

        protected global::System.Web.UI.WebControls.HiddenField hfCustomerEmail;

        protected global::System.Web.UI.WebControls.HiddenField hfCustomerPhone;

        protected global::System.Web.UI.WebControls.HiddenField hfSelectedTime;

        protected global::System.Web.UI.WebControls.HiddenField hfRebooking;

        protected global::System.Web.UI.WebControls.Button btnCancel;

        protected global::System.Web.UI.WebControls.Button btnBookAppointment;
    }
}
